name: spb_base

services:
  web:
    container_name: spb_base.web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./src:/spb_base/src
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    container_name: spb_base.mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - spb_base.mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 4s
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'

  testrunner:
    container_name: spb_base.testrunner
    profiles:
      - test
    build:
      context: .
      dockerfile: docker/testrunner/Dockerfile
    volumes:
      - ./src:/spb_base/src
      - ./tests:/spb_base/tests
    env_file:
      - test.env
    depends_on:
      test_mongo:
        condition: service_healthy

  test_mongo:
    container_name: spb_base.test_mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - spb_base.test_mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 4s
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'

volumes:
  spb_base.mongodata: { }
  spb_base.test_mongodata: { }